apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-ingest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.vector.dev
    chart: vector
    targetRevision: 0.38.0
    helm:
      values: |
        role: Stateless-Aggregator
        customConfig:
          api:
            enabled: true
            address: "0.0.0.0:8686"
          sources:
            rabbitmq_source:
              type: amqp
              connection_string: amqp://admin:1234@10.0.0.199:5672/%2f
              queue: esp32-logs
          sinks:
            kafka_sink:
              type: kafka
              inputs:
                - rabbitmq_source
              bootstrap_servers: prod-cluster-kafka-bootstrap.kafka.svc:9092
              topic: esp32-stream
              encoding:
                codec: json
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
