apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: yukinoli
  namespace: kafka
  labels:
    strimzi.io/cluster: prod-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: tutorial-topic
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: tutorial-topic
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: Read
        host: "*"
