apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: prod-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    config:
      auto.create.topics.enable: "true"
      allow.everyone.if.no.acl.found: "true"
      super.users: "User:ANONYMOUS"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
        - name: sha
          port: 9093
          type: loadbalancer
          tls: false
        - name: external
          port: 9094
          type: nodeport
          tls: false
    version: 4.1.1
    metadataVersion: 3.9-IV0
  entityOperator:
    userOperator: {}
    topicOperator: {}
