# vaultwarden/Chart.yaml

apiVersion: v2
name: vaultwarden-wrapper # On lui donne un nom pour montrer que c'est notre wrapper
description: Mon wrapper pour déployer le chart Vaultwarden officiel.
type: application
version: 0.1.0 # La version de notre propre configuration

dependencies:
  # On déclare ici le VRAI chart qu'on veut déployer
  - name: vaultwarden
    version: "4.2.0" # La version du chart distant qu'on veut
    repository: "https://charts.gabe565.com"

  # Et on déclare sa dépendance "common" comme on l'avait vu
  - name: common
    version: "1.4.0"
    repository: "https://charts.gabe565.com"
