# vaultwarden/Chart.yaml

apiVersion: v2
name: vaultwarden-wrapper
description: Mon wrapper pour déployer le chart Vaultwarden officiel.
type: application
version: 0.1.0

dependencies:
  # La dépendance pour Vaultwarden (celle-ci était correcte)
  - name: vaultwarden
    version: "0.16.1"
    repository: "https://charts.gabe565.com"


