service:
  # -- Configures service settings for the chart. Normally this does not need to be modified.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080
      websocket:
        enabled: false
        port: 3012

ingress:
  enabled: true
  host: vaultwarden.yukino.li
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: vaultwarden-tls
persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: false
    retain: true
    storageClass: "vaultwarden-data"
    accessMode: ReadWriteOnce
    size: 10Gi

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/main/bitnami/postgresql)
# @default -- See [values.yaml](./values.yaml)
postgresql:
  enabled: false
  auth:
    database: vaultwarden
    postgresPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi

# -- Enable and configure mariadb database subchart under this key.
#    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/main/bitnami/mariadb)
# @default -- See [values.yaml](./values.yaml)
mariadb:
  enabled: false
  auth:
    database: vaultwarden
    username: vaultwarden
    password: changeme
    rootPassword: changeme
  primary:
    persistence:
      enabled: false
      # storageClass: ""
      # size: 8Gi

podSecurityContext:
  # -- Run as `nobody` user
  runAsUser: 65534
  # -- Run as `nobody` group
  runAsGroup: 65534
  # -- Volume binds will be granted to `nobody` group
  fsGroup: 65534
