apiVersion: apps/v1
kind: Deployment
metadata:
  # CHANGEMENT: On utilise directement le nom de la release
  name: {{ .Release.Name }}
  labels:
    # CHANGEMENT: On définit des labels simples ici
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.ioio/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # CHANGEMENT: On utilise les mêmes labels simples pour la sélection
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        # CHANGEMENT: Et ici aussi
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
