{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 8 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: redirect-to-https # Le nom du middleware qu'on a créé !
          namespace: {{ .Release.Namespace }}
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
