apiVersion: v1
kind: Service
metadata:
  # CHANGEMENT: On utilise directement le nom de la release
  name: {{ .Release.Name }}
  labels:
    # CHANGEMENT: On définit des labels simples ici
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    # CHANGEMENT: On utilise les mêmes labels simples pour la sélection
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
