annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
apiVersion: v2
appVersion: 0.17.0
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.6.12
description: The to-do app to organize your life
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/vikunja
icon: https://s7.gifyu.com/images/GifCroppedTran.gif
keywords:
- vikunja
- to-do
- tasks
- calendar
- kanban
maintainers:
- email: k8s-at-home@xpander.eml.cc
  name: auricom
name: vikunja
sources:
- https://kolaente.dev/vikunja/api
- https://kolaente.dev/vikunja/frontend
- https://hub.docker.com/r/vikunja/api
- https://hub.docker.com/r/vikunja/frontend
- https://vikunja.io/docs/
version: 6.1.2
