# Valeurs par défaut pour le service music-app
musicApp:
  image:
    repository: registry.gitlab.com/cedric.duboille/music/music-app # Adapte si besoin
    tag: 5deabe92f0c3e262d6ab24b403483dd72228ada3
  service:
    port: 8000
# Configuration de l'Ingress (la porte d'entrée)
nginx:
  image:
    repository: registry.gitlab.com/cedric.duboille/music/nginx # Adapte si besoin
    tag: 5deabe92f0c3e262d6ab24b403483dd72228ada3
  service:
    port: 80
# Configuration de l'Ingress (la porte d'entrée)
ingress:
  enabled: true
  className: "nginx"
  host: nginx.yukino.li
  # --- NOUVEAU : On ajoute les annotations pour Traefik et Cert-Manager ---
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  # --- NOUVEAU : On configure le certificat TLS ---
  tls:
    enabled: true
    # Le nom du secret où Cert-Manager va stocker le certificat
    secretName: nginx-yukino-li-tls
    hosts:
      - nginx.yukino.li
# --- NOUVEAU : On ajoute la configuration pour le PVC existant ---
persistence:
  existingClaim: "airsonic-music2-pvc"
