# Fichier de l'Application ArgoCD à appliquer
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    # Le namespace où tu veux installer Miniflux
    namespace: miniflux 
  
  # C'est la partie la plus importante. On vise directement le dépôt Helm.
  source:
    # L'URL du dépôt Helm OFFICIEL de Miniflux
    repoURL: 'https://miniflux.github.io/helm-charts/'
    # Le nom du chart dans le dépôt
    chart: 'miniflux'
    # La version du chart que tu veux déployer (vérifie la dernière dispo)
    targetRevision: '3.0.0'
    
