# values.yaml corrigé pour Miniflux
#image:
#  repository: ghcr.io/miniflux/miniflux
#  tag: "2.1.3"
#  pullPolicy: IfNotPresent

env:
  CREATE_ADMIN: 1
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: "admin39"
  BASE_URL: "https://mini.yukino.li"
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # La structure correcte pour le host
    hosts: # <- avec un 's', c'est une liste
      - host: mini.yukino.li
        paths:
          - path: /
            pathType: Prefix
    # La structure correcte pour le tls
    tls: # <- C'est aussi une liste
      - hosts:
          - mini.yukino.li
        secretName: mini-tls

