apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/CamilleAuLit/prod.git"
    targetRevision: HEAD
    # On pointe précisément vers le dossier du chart chaos
    path: app/chaos-mesh
    # On précise à ArgoCD que c'est un chart Helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: chaos # Ou le namespace où tu veux déployer chaos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - Replace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
    - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
