apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/CamilleAuLit/prod.git"
    targetRevision: HEAD
    # On pointe précisément vers le dossier du chart gitlab-runner
    path: app/gitlab-runner
    # On précise à ArgoCD que c'est un chart Helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab-runner # Ou le namespace où tu veux déployer gitlab-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
