# Dans ton fichier argocd/vaultwarden-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  # ...
spec:
  # ...
  source:
    repoURL: '...'
    path: '...'
    targetRevision: '...'
    helm:
      # Pour ce test, tu peux commenter ou supprimer la ligne valueFiles
      # pour être sûre qu'elle n'interfère pas.
      # valueFiles:
      #  - 'values.yaml'

      # Ajoute cette section et colle tes valeurs dessous.
      # Attention, la première ligne ("service:") doit être indentée !
      values: |
        service:
          main:
            ports:
              http:
                port: 8080
              websocket:
                enabled: false
                port: 3012
        ingress:
          enabled: true
          host: vaultwarden.yukino.li
          annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls:
            enabled: true
            secretName: vaultwarden-tls
        persistence:
          data:
            enabled: true
            retain: true
            storageClass: "vaultwarden-data"
            accessMode: ReadWriteOnce
            size: 10Gi
        postgresql:
          enabled: false
          auth:
            database: vaultwarden
            postgresPassword: changeme
          primary:
            persistence:
              enabled: false
        mariadb:
          enabled: false
          auth:
            database: vaultwarden
            username: vaultwarden
            password: changeme
            rootPassword: changeme
          primary:
            persistence:
              enabled: false
        podSecurityContext:
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
        env:
          ADMIN_TOKEN: "5yy3UCtqVT4uZlmTMHEYXiXT9b9M67XkswvBLK18nwIwGpgr6sMczveQD41VCWXT"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vaultwarden

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
