apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/CamilleAuLit/prod.git"
    targetRevision: HEAD
    # On pointe précisément vers le dossier du chart vaultwarden
    path: app/vaultwarden
    # On précise à ArgoCD que c'est un chart Helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vaultwarden # Ou le namespace où tu veux déployer vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
