apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.vector.dev
    chart: vector
    targetRevision: 0.38.0
    helm:
      values: |
        role: Agent  # <--- IMPORTANT : Mode Agent (DaemonSet)

        customConfig:
          data_dir: "/vector-data-dir"
          api:
            enabled: true
            address: "0.0.0.0:8686"
          # 1. SOURCE : On aspire les logs Kubernetes locaux
          sources:
            k8s_logs:
              type: "kubernetes_logs"
          # 2. SINK : On envoie tout dans Kafka
          sinks:
            to_kafka:
              type: "kafka"
              inputs: ["k8s_logs"]
              bootstrap_servers: "prod-cluster-kafka-bootstrap.kafka.svc:9092"
              topic: "k8s-logs"     # Le nouveau topic
              encoding:
                codec: "json"       # On garde le format JSON structuré
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
