apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airsonic.fullname" . }}
  labels:
    {{- include "airsonic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "airsonic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airsonic.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 4040
        volumeMounts:
        - name: airsonic-data
          mountPath: /config
        - name: airsonic-music
          mountPath: /music
        - name: airsonic-music1
          mountPath: /music1
        - name: airsonic-music2
          mountPath: /music2
      volumes:
        - name: airsonic-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.claimName }}
        - name: airsonic-music
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.music.claimName }}
        - name: airsonic-music1
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.music1.claimName }}
        - name: airsonic-music2
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.music2.claimName }}
