apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-aggregator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.vector.dev
    chart: vector
    targetRevision: 0.38.0
    helm:
      values: |
        role: Stateless-Aggregator

        # On force l'image Debian pour avoir le support MQTT complet
        image:
          repository: timberio/vector
          tag: 0.43.0-debian
          pullPolicy: IfNotPresent

        customConfig:
          data_dir: "/vector-data-dir"
          api:
            enabled: true
            address: "0.0.0.0:8686"

          # --- SOURCES (INPUT) ---
          sources:
            kafka_source:
              type: "kafka"
              bootstrap_servers: "prod-cluster-kafka-bootstrap.kafka.svc:9092"
              topics:
                - k3s-logs
                - esp32-stream
              group_id: "vector-k8s-group"
              decoding:
                codec: "json"

          # --- SINKS (OUTPUT) ---
          sinks:
            # Ton sink principal pour les logs Kafka
            loki_sink:
              type: "loki"
              inputs: ["kafka_source"]
              endpoint: "http://loki.monitoring.svc:3100"
              encoding:
                codec: "json"
              labels:
                source: "kafka-vector"
                # Ajout des labels dynamiques
                namespace: '{{ "{{" }} kubernetes.pod_namespace }}'
                pod: '{{ "{{" }} kubernetes.pod_name }}'

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
