apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-aggregator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.vector.dev
    chart: vector
    targetRevision: 0.38.0
    helm:
      values: |
        role: Stateless-Aggregator
        image:
          repository: timberio/vector
          tag: 0.43.0-debian
          pullPolicy: IfNotPresent

        customConfig:
          data_dir: "/vector-data-dir"
          api:
            enabled: true
            address: "0.0.0.0:8686"

          # --- 1. SOURCES (On lit Kafka) ---
          sources:
            kafka_source:
              type: "kafka"
              bootstrap_servers: "prod-cluster-kafka-bootstrap.kafka.svc:9092"
              topics: ["k3s-logs", "esp32-stream"]
              group_id: "vector-k8s-group"
              decoding:
                codec: "json"

          # --- 2. TRANSFORMS (La réparation magique) ---
          transforms:
            fix_iot_labels:
              type: "remap"
              inputs: ["kafka_source"] # On prend la source Kafka
              source: |
                # Si le namespace est vide (cas ESP32), on met 'monitoring'
                .kubernetes.pod_namespace = .kubernetes.pod_namespace || "monitoring"
                # Si le nom du pod est vide, on met 'esp32-device'
                .kubernetes.pod_name = .kubernetes.pod_name || "esp32-device"

          # --- 3. SINKS (On envoie à Loki) ---
          sinks:
            loki_sink:
              type: "loki"
              # IMPORTANT : On écoute le transform, pas la source direct !
              inputs: ["fix_iot_labels"]
              endpoint: "http://loki.monitoring.svc:3100"
              encoding:
                codec: "json"
              labels:
                source: "kafka-vector"
                # Maintenant ces champs existent forcément grâce au transform
                namespace: '{{ "{{" }} kubernetes.pod_namespace }}'
                pod: '{{ "{{" }} kubernetes.pod_name }}'

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
